class Webpack
  # This returns a string pointing to a webpack bundle.  In development,
  # this is generated by the webpack watch task; in production it's
  # a compiled hashed file, so we read the hash from the manifest file.
  def self.bundle(name)
    if Rails.env.production?
      @production_manifest ||= JSON.parse(File.read('public/build/manifest.json'))
      filename = @production_manifest[name]
      "/build/#{filename}"
    else
      "/dev/#{name}"
    end
  end
end
