# This file is autogenerated. Do not edit it by hand. Regenerate it with:
#   srb rbi gems

# typed: strong
#
# If you would like to make changes to this file, great! Please create the gem's shim here:
#
#   https://github.com/sorbet/sorbet-typed/new/master?filename=lib/authtrail/all/authtrail.rbi
#
# authtrail-0.1.1
module AuthTrail
  def self.exclude_method; end
  def self.exclude_method=(arg0); end
  def self.geocode; end
  def self.geocode=(arg0); end
  def self.safely(default: nil); end
  def self.track(strategy:, scope:, identity:, success:, request:, user: nil, failure_reason: nil); end
  def self.track_method; end
  def self.track_method=(arg0); end
end
class AuthTrail::Engine < Rails::Engine
end
module AuthTrail::Manager
  def self.after_set_user(user, auth, opts); end
  def self.before_failure(env, opts); end
  def self.detect_strategy(auth); end
end
