# This file is autogenerated. Do not edit it by hand. Regenerate it with:
#   srb rbi gems

# typed: strong
#
# If you would like to make changes to this file, great! Please create the gem's shim here:
#
#   https://github.com/sorbet/sorbet-typed/new/master?filename=lib/aws-sdk-resources/all/aws-sdk-resources.rbi
#
# aws-sdk-resources-2.11.33
module Aws
end
module Aws::Resources
end
