# This file is autogenerated. Do not edit it by hand. Regenerate it with:
#   srb rbi gems

# typed: strong
#
# If you would like to make changes to this file, great! Please create the gem's shim here:
#
#   https://github.com/sorbet/sorbet-typed/new/master?filename=lib/declarative-option/all/declarative-option.rbi
#
# declarative-option-0.1.0
module Declarative
  def self.Option(value, options = nil); end
end
module Declarative::Callable
end
class Declarative::Option
  def call(value, options = nil); end
  def callable?(value, options); end
  def lambda_for_callable(value, options); end
  def lambda_for_proc(value, options); end
  def lambda_for_static(value, options); end
  def lambda_for_symbol(value, options); end
end
