# This file is autogenerated. Do not edit it by hand. Regenerate it with:
#   srb rbi gems

# typed: strong
#
# If you would like to make changes to this file, great! Please create the gem's shim here:
#
#   https://github.com/sorbet/sorbet-typed/new/master?filename=lib/descriptive-statistics/all/descriptive-statistics.rbi
#
# descriptive-statistics-2.2.0
module DescriptiveStatistics
  include DescriptiveStatistics::AllMethods
end
module DescriptiveStatistics::CentralTendency
  def mean; end
  def median; end
  def mode; end
  def sum(identity = nil, &block); end
end
module DescriptiveStatistics::Dispersion
  def percentile_from_value(value); end
  def range; end
  def value_from_percentile(percentile); end
end
module DescriptiveStatistics::Spread
  def population_standard_deviation; end
  def population_variance; end
  def relative_standard_deviation; end
  def standard_deviation; end
  def variance; end
  def zscore; end
end
module DescriptiveStatistics::Shape
  def cubed_standard_deviation; end
  def kurtosis; end
  def quarted_standard_deviation; end
  def skewness; end
  def sum_cubed_deviation; end
  def sum_quarted_deviation; end
end
module DescriptiveStatistics::AllMethods
  include DescriptiveStatistics::CentralTendency
  include DescriptiveStatistics::Dispersion
  include DescriptiveStatistics::Shape
  include DescriptiveStatistics::Spread
end
class DescriptiveStatistics::Stats < SimpleDelegator
  include DescriptiveStatistics::AllMethods
end
