# This file is autogenerated. Do not edit it by hand. Regenerate it with:
#   srb rbi gems

# typed: strong
#
# If you would like to make changes to this file, great! Please create the gem's shim here:
#
#   https://github.com/sorbet/sorbet-typed/new/master?filename=lib/ipcat/all/ipcat.rbi
#
# ipcat-2.0.20
class IPCat
  def self.bsearch(needle, haystack = nil, first = nil, last = nil); end
  def self.classify(ip); end
  def self.datacenter?(ip); end
  def self.ip_to_integer(ip); end
  def self.load!; end
  def self.load_csv!(path = nil); end
  def self.ranges; end
  def self.reset_ranges!(new_ranges = nil); end
end
class IPCat::IPRange
  def <=>(obj); end
  def compare_with_integer(i); end
  def first; end
  def first=(arg0); end
  def initialize(first, last, name = nil, url = nil); end
  def last; end
  def last=(arg0); end
  def name; end
  def name=(arg0); end
  def url; end
  def url=(arg0); end
end
