# This file is autogenerated. Do not edit it by hand. Regenerate it with:
#   srb rbi gems

# typed: strong
#
# If you would like to make changes to this file, great! Please create the gem's shim here:
#
#   https://github.com/sorbet/sorbet-typed/new/master?filename=lib/moneta/all/moneta.rbi
#
# moneta-0.8.1
module Moneta
  def self.build(&block); end
  def self.new(name, options = nil); end
end
module Moneta::Adapters
end
