# This file is autogenerated. Do not edit it by hand. Regenerate it with:
#   srb rbi gems

# typed: strong
#
# If you would like to make changes to this file, great! Please create the gem's shim here:
#
#   https://github.com/sorbet/sorbet-typed/new/master?filename=lib/oj_mimic_json/all/oj_mimic_json.rbi
#
# oj_mimic_json-1.0.1
class Object < BasicObject
  def JSON(*arg0); end
  def self.JSON(*arg0); end
  def to_json(options = nil); end
end
class OpenStruct
  def self.json_create(h); end
end
class BigDecimal < Numeric
  def self.new(*arg0); end
end
class Complex < Numeric
  def self.polar(*arg0); end
end
class Date
  def self.json_create(h); end
end
class DateTime < Date
  def self.json_create(h); end
end
class Exception
  def self.json_create(h); end
end
class Range
  def self.json_create(h); end
end
class Rational < Numeric
  def self.json_create(h); end
end
class Regexp
  def self.json_create(h); end
end
class Struct
  def self.json_create(h); end
end
class Symbol
  def self.json_create(h); end
end
class Time
  def self.json_create(h); end
end
module JSON
  def [](*arg0); end
  def create_id; end
  def create_id=(arg0); end
  def state; end
end
