# This file is autogenerated. Do not edit it by hand. Regenerate it with:
#   srb rbi gems

# typed: strong
#
# If you would like to make changes to this file, great! Please create the gem's shim here:
#
#   https://github.com/sorbet/sorbet-typed/new/master?filename=lib/probability/all/probability.rbi
#
# probability-1.0.0
module Probability
end
class Integer < Numeric
  def in(number, &block); end
end
