# This file is autogenerated. Do not edit it by hand. Regenerate it with:
#   srb rbi gems

# typed: strong
#
# If you would like to make changes to this file, great! Please create the gem's shim here:
#
#   https://github.com/sorbet/sorbet-typed/new/master?filename=lib/retriable/all/retriable.rbi
#
# retriable-3.1.2
module Retriable
  def config; end
  def configure; end
  def retriable(opts = nil); end
  def self.config; end
  def self.configure; end
  def self.retriable(opts = nil); end
  def self.with_context(context_key, options = nil, &block); end
  def with_context(context_key, options = nil, &block); end
end
class Retriable::ExponentialBackoff
  def base_interval; end
  def base_interval=(arg0); end
  def initialize(opts = nil); end
  def intervals; end
  def max_interval; end
  def max_interval=(arg0); end
  def multiplier; end
  def multiplier=(arg0); end
  def rand_factor; end
  def rand_factor=(arg0); end
  def randomize(interval); end
  def tries; end
  def tries=(arg0); end
end
class Retriable::Config
  def base_interval; end
  def base_interval=(arg0); end
  def contexts; end
  def contexts=(arg0); end
  def initialize(opts = nil); end
  def intervals; end
  def intervals=(arg0); end
  def max_elapsed_time; end
  def max_elapsed_time=(arg0); end
  def max_interval; end
  def max_interval=(arg0); end
  def multiplier; end
  def multiplier=(arg0); end
  def on; end
  def on=(arg0); end
  def on_retry; end
  def on_retry=(arg0); end
  def rand_factor; end
  def rand_factor=(arg0); end
  def sleep_disabled; end
  def sleep_disabled=(arg0); end
  def timeout; end
  def timeout=(arg0); end
  def to_h; end
  def tries; end
  def tries=(arg0); end
end
