# This file is autogenerated. Do not edit it by hand. Regenerate it with:
#   srb rbi gems

# typed: strong
#
# If you would like to make changes to this file, great! Please create the gem's shim here:
#
#   https://github.com/sorbet/sorbet-typed/new/master?filename=lib/zxcvbn-js/all/zxcvbn-js.rbi
#
# zxcvbn-js-4.4.3
module Zxcvbn
  def test(password, user_inputs = nil); end
  extend Zxcvbn
end
class Zxcvbn::Tester
  def initialize; end
  def test(password, user_inputs = nil); end
end
