AllCops:
  DisabledByDefault: true
  Exclude:
    - 'bin/**/*'
    - 'config/**/*'
    - 'db/**/*'
    - 'docs/**/*'
    - 'log/**/*'
    - 'node_modules/**/*'
    - 'public/**/*'
    - 'scripts/**/*'
    - 'vendor/**/*'
    - 'x2_export/**/*'

Layout/TrailingWhitespace:
  Enabled: true

Layout/TrailingEmptyLines:
  Enabled: true

Layout/BlockEndNewline:
  Enabled: true

Layout/EmptyLineBetweenDefs:
  Enabled: true

Layout/EmptyLines:
  Enabled: true

Layout/IndentationStyle:
  Enabled: true

Layout/ConditionPosition:
  Enabled: true

Layout/SpaceInsideStringInterpolation:
  Enabled: true

Lint/AssignmentInCondition:
  Enabled: true

Lint/Debugger:
  Enabled: true

Lint/DeprecatedClassMethods:
  Enabled: true

Lint/DuplicateMethods:
  Enabled: true

Lint/SuppressedException:
  Enabled: true

Lint/InheritException:
  Enabled: true

Lint/Loop:
  Enabled: true

Lint/UnreachableCode:
  Enabled: true

Style/CaseEquality:
  Enabled: true
