SELECT
  STD_OID,
  STD_ID_STATE,
  CND_INCIDENT_CODE,
  CND_INCIDENT_DATE,
  CND_INCIDENT_TIME,
  CND_ACTIVITY_DATE,
  CND_MEETING_DATE,
  CND_INCIDENT_LOCATION,
  CND_INCIDENT_DESCRIPTION,
  CND_STF_OID_REFERRAL,
  CND_STF_OID_OWNER
FROM student
INNER JOIN student_conduct_incident
  ON student.STD_OID=student_conduct_incident.CND_STD_OID
WHERE STD_ENROLLMENT_STATUS = 'Active'
AND STD_ID_STATE IS NOT NULL
AND STD_OID IS NOT NULL