SELECT
  STD_OID,
  STD_ID_STATE,
  std_name_view,
  STD_HOME_LANGUAGE_CODE,
  STD_SKL_OID,
  STD_GRADE_LEVEL,
  STD_HOMEROOM
FROM student
WHERE STD_ENROLLMENT_STATUS = 'Active'
AND STD_ID_STATE IS NOT NULL
AND STD_OID IS NOT NULL