# This was originally generated by Administrate.
#
# To customize the behavior of this controller,
# simply overwrite any of the RESTful actions.
module Admin
  class EducatorsController < Admin::ApplicationController
    before_action :set_default_params!

    # override and disable
    def create
      raise Exceptions::EducatorNotAuthorized
    end

    # override and disable
    def new
      raise Exceptions::EducatorNotAuthorized
    end

    # override and disable
    def destroy
      raise Exceptions::EducatorNotAuthorized
    end

    # allow
    def index
      super
    end

    # allow
    def show
      super
    end

    # allow
    def edit
      super
    end

    # allow, and update index after any changes
    def update
      super
      EducatorSearchbar.update_student_searchbar_json!(requested_resource)
    end

    # This was added, and unrelated to administrate.
    def authorization
      educators_with_includes = Educator.all.includes(:educator_labels, :school, :sections, {homeroom: [:school, :students]})
      @sensitive_educators = sorted_sensitive_educators(educators_with_includes)
      @sorted_educators, @navbar_links_map = sort_list_with_navbar_links(educators_with_includes)
      nil
    end

    private
    # override
    def resource_params
      params["educator"]["grade_level_access"] = params["educator"]["grade_level_access"].try(:keys) || []

      params.require("educator").permit(*dashboard.permitted_attributes, grade_level_access: [])
    end

    def set_default_params!
      params[:order] ||= "full_name"
      params[:direction] ||= "desc"
    end

    def sort_list_with_navbar_links(educators)
      navbar_links_map = {}
      sorted_educators = educators.sort_by do |educator|
        navbar_links = PathsForEducator.new(educator).navbar_links
        navbar_links_map[educator.id] = navbar_links
        [
          educator.active? ? 0 : 1,
          -1 * navbar_links.size,
          navbar_links.keys
        ]
      end
      [sorted_educators, navbar_links_map]
    end

    def sorted_sensitive_educators(educators)
      filtered = educators.select do |educator|
        educator.active? && (
          educator.can_set_districtwide_access ||
          educator.can_view_restricted_notes ||
          educator.districtwide_access ||
          educator.admin
        )
      end

      filtered.sort_by do |educator|
        [
          educator.active? ? 0 : 1,
          educator.can_set_districtwide_access ? 0 : 1,
          educator.can_view_restricted_notes ? 0 : 1,
          educator.districtwide_access ? 0 : 1,
          educator.admin ? 0 : 1
        ]
      end
    end
  end
end
