class DistrictConfig

  # Filenames for nightly remote data import
  FILENAME_FOR_ASSESSMENT_IMPORT = ENV.fetch('FILENAME_FOR_ASSESSMENT_IMPORT')

  FILENAME_FOR_STUDENTS_IMPORT = ENV.fetch('FILENAME_FOR_STUDENTS_IMPORT')

  FILENAME_FOR_STUDENT_AVERAGES_IMPORT = ENV.fetch('FILENAME_FOR_STUDENT_AVERAGES_IMPORT')

  FILENAME_FOR_STUDENTS_SECTION_ASSIGNMENT_IMPORT = ENV.fetch('FILENAME_FOR_STUDENTS_SECTION_ASSIGNMENT_IMPORT')

  FILENAME_FOR_STAR_READING_IMPORT = ENV.fetch('FILENAME_FOR_STAR_READING_IMPORT')

  FILENAME_FOR_EDUCATORS_IMPORT = ENV.fetch('FILENAME_FOR_EDUCATORS_IMPORT')

  FILENAME_FOR_EDUCATOR_SECTION_ASSIGNMENT_IMPORT = ENV.fetch('FILENAME_FOR_EDUCATOR_SECTION_ASSIGNMENT_IMPORT')

  FILENAME_FOR_BEHAVIOR_IMPORT = ENV.fetch('FILENAME_FOR_BEHAVIOR_IMPORT')

  FILENAME_FOR_COURSE_SECTION_IMPORT = ENV.fetch('FILENAME_FOR_COURSE_SECTION_IMPORT')

  FILENAME_FOR_ATTENDANCE_IMPORT = ENV.fetch('FILENAME_FOR_ATTENDANCE_IMPORT')

end
