class DisciplineIncident < ActiveRecord::Base
  belongs_to :student
  validates_presence_of :student, :occurred_at

  def self.example_incident_codes
    [
      "?",
      "AS",
      "AWOL",
      "Alcohol-Possession",
      "Assault",
      "Attendance-Other",
      "Bullying",
      "CBMD",
      "CC",
      "CP",
      "CSD",
      "CTD",
      "Cell Phone",
      "Cheating",
      "CutExcess",
      "DI",
      "DSR",
      "Defiant",
      "Disorderly Conduct",
      "Displays Affection",
      "Disruptive",
      "Drugs-Marij possess",
      "Drugs-Marijuana use",
      "Drugs-Paraphernalia",
      "Drugs-Possession",
      "Drugs-Sale Of",
      "Drugs-Suspicion",
      "Drugs-Use",
      "ET",
      "FO",
      "Felony Conviction",
      "Forging abs excuse",
      "Gesture",
      "Harass-Nonsexual",
      "Harass-Other",
      "ID",
      "IRMK",
      "Insubordination",
      "LeftClass",
      "MarijuanaUse",
      "Medication-Other",
      "NI",
      "OBI",
      "OBO",
      "OT",
      "Obscene behavior",
      "Obscene elec msg",
      "Obscene gestures",
      "Obscene language",
      "Obscene written msg",
      "Other Offenses",
      "Physical Altercation",
      "Profanity",
      "RCOP",
      "RD",
      "RHOUSE",
      "RIDH",
      "SW",
      "Sexual Offenses",
      "Skipping class",
      "Suicide-Other",
      "Suspendable",
      "TR",
      "Tardiness",
      "Threat-School, Other",
      "Tobacco-Other",
      "Tobacco-Use",
      "Truancy",
      "VCP",
      "VIOL-Arson",
      "VIOL-Assault Alterc",
      "VIOL-Assault Battery",
      "VIOL-Fighting",
      "VIOL-Harass Sexual",
      "VIOL-Other Incident",
      "VIOL-Robbery Threat",
      "VIOL-Sexual Battery",
      "VIOL-Theft",
      "VIOL-Threat Electron",
      "VIOL-Threat Intimid",
      "VIOL-Threat Other",
      "VIOL-Threat Physical",
      "VIOL-Threat Terror",
      "VIOL-Threat Verbal",
      "VIOL-Threat Written",
      "VIOL-Vandalism",
      "VIOL-Vandalism Other",
      "VIOL-Vandalism Prsnl",
      "VIOL-Vandalism Skl",
      "Violation of Rules",
      "WEAPON-Explosive",
      "WEAPON-Gun",
      "WEAPON-Knife",
      "WEAPON-Other",
      "WEAPON-OtherFireArm",
      "Wander",
      "Weapons Possession",
      "XT"
    ]
  end
end
